package controllers_test

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	schedulingv1 "github.com/8terbahn/distribute_gpu_scheduler/api/v1"
	"github.com/8terbahn/distribute_gpu_scheduler/internal/controllers"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

var (
	cfg       *rest.Config
	k8sClient client.Client
	testEnv   *envtest.Environment
	ctx       context.Context
	cancel    context.CancelFunc
)

func TestControllers(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Controller Suite")
}

var _ = BeforeSuite(func() {
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))
	ctx, cancel = context.WithCancel(context.TODO())

	testEnv = &envtest.Environment{
		// CRDs generated by `make generate manifests` are placed in config/crd/bases.
		CRDDirectoryPaths:     []string{filepath.Join("..", "..", "config", "crd", "bases")},
		ErrorIfCRDPathMissing: true,
	}

	var err error
	cfg, err = testEnv.Start()
	Expect(err).NotTo(HaveOccurred())

	Expect(schedulingv1.AddToScheme(scheme.Scheme)).To(Succeed())

	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
	Expect(err).NotTo(HaveOccurred())

	mgr, err := ctrl.NewManager(cfg, ctrl.Options{Scheme: scheme.Scheme})
	Expect(err).NotTo(HaveOccurred())

	Expect((&controllers.GPUWorkloadReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
		Log:    ctrl.Log.WithName("GPUWorkload"),
	}).SetupWithManager(mgr)).To(Succeed())

	Expect((&controllers.GPUPoolReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr)).To(Succeed())

	go func() {
		defer GinkgoRecover()
		Expect(mgr.Start(ctx)).To(Succeed())
	}()
})

var _ = AfterSuite(func() {
	cancel()
	Expect(testEnv.Stop()).To(Succeed())
})

// --- Integration tests ---

var _ = Describe("GPUWorkload controller", func() {
	const (
		workloadName = "test-workload"
		poolName     = "test-pool"
		namespace    = "default"
		timeout      = 10 * time.Second
		interval     = 250 * time.Millisecond
	)

	It("should assign a workload to a matching pool", func() {
		By("creating a GPUPool")
		pool := &schedulingv1.GPUPool{
			ObjectMeta: metav1.ObjectMeta{
				Name:      poolName,
				Namespace: namespace,
			},
			Spec: schedulingv1.GPUPoolSpec{
				GPUType:    "A100",
				TotalUnits: 4,
			},
		}
		Expect(k8sClient.Create(ctx, pool)).To(Succeed())

		// Seed available units (normally done by GPUPoolReconciler).
		pool.Status.AvailableUnits = 4
		pool.Status.AllocatedUnits = 0
		Expect(k8sClient.Status().Update(ctx, pool)).To(Succeed())

		By("creating a GPUWorkload")
		workload := &schedulingv1.GPUWorkload{
			ObjectMeta: metav1.ObjectMeta{
				Name:      workloadName,
				Namespace: namespace,
			},
			Spec: schedulingv1.GPUWorkloadSpec{
				Workload:       "llm_inference",
				GPURequirement: "A100",
				Priority:       7,
			},
		}
		Expect(k8sClient.Create(ctx, workload)).To(Succeed())

		By("expecting the workload to reach Assigned phase")
		Eventually(func(g Gomega) {
			var w schedulingv1.GPUWorkload
			g.Expect(k8sClient.Get(ctx,
				client.ObjectKey{Name: workloadName, Namespace: namespace}, &w,
			)).To(Succeed())
			g.Expect(w.Status.Phase).To(Equal(controllers.PhaseAssigned))
			g.Expect(w.Status.AssignedWorker).To(Equal(poolName))
		}, timeout, interval).Should(Succeed())
	})
})
