apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: gpu-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: distributed-gpu-scheduler/scheduler:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: distributed-gpu-scheduler-config
            - secretRef:
                name: distributed-gpu-scheduler-secrets
